ESD6NL.DriverSystem/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ESD6NL.DriverSystem.BLL;
using ESD6NL.DriverSystem.BLL.Interfaces;
using ESD6NL.DriverSystem.Entities;
using ESD6NL.DriverSystem.Helpers;
using ESD6NL.DriverSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Server.Kestrel.Internal.System.Collections.Sequences;

namespace ESD6NL.DriverSystem.Controllers
{
    [Authorize]
    public class CarController : BaseController
    {
        private readonly ICarService _carService;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="carService"></param>
        public CarController(ICarService carService, ITranslationService ts, IUserService us): base(ts,us)
        {
            _carService = carService;
        }

        /// <summary>
        /// Overview action result. Shows all the cars of an owner.
        /// </summary>
        /// <returns></returns>
        public IActionResult CarOverview()
        {
            IEnumerable<Car> cars = _carService.GetCarsOfUserFromAAS(getUser().citizenServiceNumber);
            var userViewModel = FillUserViewModel(cars);

            return View(userViewModel);
        }

        /// <summary>
        /// Detail action result. Shows all the details of one specific car.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Details(int id)
        {
            var car = _carService.GetCar(id);
            if (car == null) return NotFound();
            var carViewModel = FillCarViewModel(car);

            return View(carViewModel);
        }

        public UserViewModel FillUserViewModel(IEnumerable<Car> car)
        {
            UserViewModel userViewModel = new UserViewModel();
            userViewModel.cars.AddRange(car);
            return userViewModel;
        }

        public CarViewModel FillCarViewModel(Car car)
        {
            CarViewModel carViewModel = new CarViewModel();
            carViewModel.car = car;
            return carViewModel;
        }
    }
}

ESD6NL.DriverSystem/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using ESD6NL.DriverSystem.BLL;
using ESD6NL.DriverSystem.BLL.Interfaces;
using ESD6NL.DriverSystem.Entities;
using ESD6NL.DriverSystem.Helpers;
using ESD6NL.DriverSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ESD6NL.DriverSystem.Controllers
{
    [Authorize]
    public class InvoiceController : BaseController
    {
        private readonly IInvoiceService _invoiceService;
        private readonly IRowService _rowService;

        /// <summary>
        /// Contructor
        /// </summary>
        /// <param name="invoiceService"></param>
        public InvoiceController(IInvoiceService invoiceService, ITranslationService ts, IUserService userService, IRowService rowService) : base(ts,userService)
        {
            _invoiceService = invoiceService;
            _userService = userService;
            _rowService = rowService;
        }

        /// <summary>
        /// Function for getting the overview information of invoices. 
        /// </summary>
        /// <returns>invoice overview view</returns>
        public IActionResult InvoiceOverview()
        {

            var invoice = _invoiceService.GetAllInvoices(getUser().citizenServiceNumber) as List<Invoice>;
            var userViewModel = FillUserViewModel(invoice);

            return View(userViewModel);
        }

        public IActionResult Map(int id)
        {
            string referer = Request.Headers["Referer"];
            string[] refe = referer.Split("/");
            string invoiceId = refe.Last();
            var row = _rowService.getSpecificRow(id);
            RowModel model = new RowModel
            {
                costs = row.costs,
                rowId = row.rowId,
                route = row.navigatedRoutes,
                dayOfWeek = row.dayOfWeek,
                date = row.date,
                km = row.km,
                InvoiceId = invoiceId
            };
            return View(model);
        }

        public IActionResult PaymentProcessed()
        {
            string auth = "ncFfxRN13LECpr3gI2SXXAWJpv3CW5nC_SiovkaDuPdVhrVx_TBAs0me9Hu";
            string txToken = Request.Query["tx"].ToString();
            string query = "cmd=_notify-synch&tx=" + txToken + "&at=" + auth;

            HttpWebRequest req = (HttpWebRequest)WebRequest.Create("https://www.sandbox.paypal.com/cgi-bin/webscr");

            req.Method = "POST";
            req.ContentType = "application/x-www-form-urlencoded";
            req.ContentLength = query.Length;

            //Send the request to PayPal and get the response
            StreamWriter streamOut = new StreamWriter(req.GetRequestStream(), System.Text.Encoding.ASCII);
            streamOut.Write(query);
            streamOut.Close();
            StreamReader streamIn = new StreamReader(req.GetResponse().GetResponseStream());
            string strResponse = streamIn.ReadToEnd();
            streamIn.Close();

            Dictionary<string, string> results = new Dictionary<string, string>();
            if (strResponse != "")
            {
                StringReader reader = new StringReader(strResponse);
                string line = reader.ReadLine();

                if (line == "SUCCESS")
                {

                    while ((line = reader.ReadLine()) != null)
                    {
                        results.Add(line.Split('=')[0], line.Split('=')[1]);

                    }
                    string paidInvoice = results["item_name"];
                    Regex rx = new Regex(@"[^0-9]");
                    string invoicenr = rx.Replace(paidInvoice, "");
                    int paidInvoiceId = Int32.Parse(invoicenr);

                    _invoiceService.updateInvoice(paidInvoiceId);
                }
            }

            

            return RedirectToAction("InvoiceOverview");
        }
        /// <summary>
        /// Function for getting the detailed view of one invoice
        /// </summary>
        /// <returns></returns>
        public IActionResult Details(int id)
        {
            var invoice = _invoiceService.GetInvoice(id);
            if (invoice == null) return NotFound();
            var invoiceViewModel = InvoiceHelpercs.FillInvoiceViewModel(invoice);

            return View(invoiceViewModel);
        }

        public UserViewModel FillUserViewModel(IEnumerable<Invoice> invoices)
        {
            UserViewModel userViewModel = new UserViewModel();
            userViewModel.invoices.AddRange(invoices);
            return userViewModel;
        }
    }
}

ESD6NL.DriverSystem/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using ESD6NL.DriverSystem.Helpers
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Rekeningrijden</title>
    
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet/less" type="text/css" href="~/css/Home.css" />
        <link rel="stylesheet/less" type="text/css" href="~/css/Header.css" />
        <script src="//cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <script src="//cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js"></script>
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="column-container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="header-brand">Rekeningrijden</a>
                </div>

                <div class="navbar-collapse collapse">
                    <div class="LoggedInNavbar">
                        <ul class="nav navbar-nav">
                            @if (AuthorizationService.AuthorizeAsync(User, "LoggedInOnly").Result.Succeeded)
                            {
                                <li><a asp-area="" asp-controller="Home" asp-action="Home">@Html.getTerm("MijnRR")</a></li>
                                <li><a asp-area="" asp-controller="Car" asp-action="CarOverview">@Html.getTerm("Auto's")</a></li>
                                <li><a asp-area="" asp-controller="Invoice" asp-action="InvoiceOverview">@Html.getTerm("Facturen")</a></li>
                                <li><a asp-area="" asp-controller="Home" asp-action="Logout">@Html.getTerm("Uitloggen")</a></li>
                            }
                        </ul>
                    </div>
                    <div class="LanguageNavbar">
                        <ul class="nav navbar-nav right">
                            <li><a asp-area="" asp-controller="Language" asp-action="ChangeLanguage" asp-route-language="NLD"> NL</a></li>
                            <li><a asp-area="" asp-controller="Language" asp-action="ChangeLanguage" asp-route-language="ENG"> EN</a></li>
                        </ul>
                    </div>
                </div>
                


            </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ESD6NL.DriverSystem</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>