ESD6NL.DriverSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ESD6NL.DriverSystem.BLL;
using ESD6NL.DriverSystem.BLL.Interfaces;
using ESD6NL.DriverSystem.Entities;
using ESD6NL.DriverSystem.Helpers;
using Microsoft.AspNetCore.Mvc;
using ESD6NL.DriverSystem.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Routing;

namespace ESD6NL.DriverSystem.Controllers
{
    public class HomeController : BaseController
    {
        private IInvoiceService _invoiceService;
        public HomeController(IUserService userService, IInvoiceService invoiceService, ITranslationService ts) : base(ts,userService)
        {
            _userService = userService;
            _invoiceService = invoiceService;
        }

        public IActionResult Index()
        {
            if (User.IsInRole("User"))
            {
                return RedirectToAction("Home", "Home");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Index(LoginModel login)
        {
            if (!ModelState.IsValid || !_userService.checkUserLogin(login.Password, login.Username)) return View(login);
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, login.Username),
                new Claim(ClaimTypes.Role, "User"),
            };

            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties();

            HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);
            User loggedInUser = _userService.getUserByUsername(login.Username);
            _userService.syncUser(loggedInUser);
            Response.Cookies.Append("Language",loggedInUser.Language);
            return RedirectToAction("Home","Home");

        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public IActionResult Home()
        {
            return View();
        }

        public IActionResult PayLastInvoice()
        {
            var invoice = _invoiceService.getLastInvoice();
            if (invoice == null) return NotFound();
            var invoiceViewModel = InvoiceHelpercs.FillInvoiceViewModel(invoice);

            return RedirectToAction("Details", new RouteValueDictionary(
            new
            {
                controller = "Invoice", action = "Details", Id = invoiceViewModel.invoiceId })); ;
            }
        }
}

ESD6NL.DriverSystem/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using ESD6NL.DriverSystem.BLL;
using ESD6NL.DriverSystem.BLL.Interfaces;
using ESD6NL.DriverSystem.Entities;
using ESD6NL.DriverSystem.Helpers;
using ESD6NL.DriverSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ESD6NL.DriverSystem.Controllers
{
    [Authorize]
    public class InvoiceController : BaseController
    {
        private readonly IInvoiceService _invoiceService;
        private readonly IRowService _rowService;

        /// <summary>
        /// Contructor
        /// </summary>
        /// <param name="invoiceService"></param>
        public InvoiceController(IInvoiceService invoiceService, ITranslationService ts, IUserService userService, IRowService rowService) : base(ts,userService)
        {
            _invoiceService = invoiceService;
            _userService = userService;
            _rowService = rowService;
        }

        /// <summary>
        /// Function for getting the overview information of invoices. 
        /// </summary>
        /// <returns>invoice overview view</returns>
        public IActionResult InvoiceOverview()
        {

            var invoice = _invoiceService.GetAllInvoices(getUser().citizenServiceNumber) as List<Invoice>;
            var userViewModel = FillUserViewModel(invoice);

            return View(userViewModel);
        }

        public IActionResult Map(int id)
        {
            string referer = Request.Headers["Referer"];
            string[] refe = referer.Split("/");
            string invoiceId = refe.Last();
            var row = _rowService.getSpecificRow(id);
            RowModel model = new RowModel
            {
                costs = row.costs,
                rowId = row.rowId,
                route = row.navigatedRoutes,
                dayOfWeek = row.dayOfWeek,
                date = row.date,
                km = row.km,
                InvoiceId = invoiceId
            };
            return View(model);
        }

        public IActionResult PaymentProcessed()
        {
            string auth = "ncFfxRN13LECpr3gI2SXXAWJpv3CW5nC_SiovkaDuPdVhrVx_TBAs0me9Hu";
            string txToken = Request.Query["tx"].ToString();
            string query = "cmd=_notify-synch&tx=" + txToken + "&at=" + auth;

            HttpWebRequest req = (HttpWebRequest)WebRequest.Create("https://www.sandbox.paypal.com/cgi-bin/webscr");

            req.Method = "POST";
            req.ContentType = "application/x-www-form-urlencoded";
            req.ContentLength = query.Length;

            //Send the request to PayPal and get the response
            StreamWriter streamOut = new StreamWriter(req.GetRequestStream(), System.Text.Encoding.ASCII);
            streamOut.Write(query);
            streamOut.Close();
            StreamReader streamIn = new StreamReader(req.GetResponse().GetResponseStream());
            string strResponse = streamIn.ReadToEnd();
            streamIn.Close();

            Dictionary<string, string> results = new Dictionary<string, string>();
            if (strResponse != "")
            {
                StringReader reader = new StringReader(strResponse);
                string line = reader.ReadLine();

                if (line == "SUCCESS")
                {

                    while ((line = reader.ReadLine()) != null)
                    {
                        results.Add(line.Split('=')[0], line.Split('=')[1]);

                    }
                    string paidInvoice = results["item_name"];
                    Regex rx = new Regex(@"[^0-9]");
                    string invoicenr = rx.Replace(paidInvoice, "");
                    int paidInvoiceId = Int32.Parse(invoicenr);

                    _invoiceService.updateInvoice(paidInvoiceId);
                }
            }

            

            return RedirectToAction("InvoiceOverview");
        }
        /// <summary>
        /// Function for getting the detailed view of one invoice
        /// </summary>
        /// <returns></returns>
        public IActionResult Details(int id)
        {
            var invoice = _invoiceService.GetInvoice(id);
            if (invoice == null) return NotFound();
            var invoiceViewModel = InvoiceHelpercs.FillInvoiceViewModel(invoice);

            return View(invoiceViewModel);
        }

        public UserViewModel FillUserViewModel(IEnumerable<Invoice> invoices)
        {
            UserViewModel userViewModel = new UserViewModel();
            userViewModel.invoices.AddRange(invoices);
            return userViewModel;
        }
    }
}

ESD6NL.DriverSystem/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ESD6NL.DriverSystem.BLL;
using ESD6NL.DriverSystem.BLL.Enums;
using ESD6NL.DriverSystem.BLL.Interfaces;
using ESD6NL.DriverSystem.Models;
using Microsoft.AspNetCore.Mvc;
using ESD6NL.DriverSystem.Entities;
using ESD6NL.DriverSystem.Helpers;
using Microsoft.AspNetCore.Identity;

namespace ESD6NL.DriverSystem.Controllers
{
    public class RegistrationController : BaseController
    {
       

        public RegistrationController(IUserService regSerivce, ITranslationService ts) : base(ts,regSerivce)
        {
        }

        /// <summary>
        /// Display of the registration view
        /// </summary>
        /// <returns>Take a guess. Hint: It's not the login view</returns>
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// What do you think the Post function in a registration controller could possibly do?!
        /// </summary>
        /// <param name="model">Its a RegistrationModel. Take a wild guess</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Index(RegistrationModel model)
        {
            User toAdd = new User {email = model.Email, userName = model.Username, password = model.Password, firstName = model.FirstName, lastName = model.LastName, citizenServiceNumber = model.CitizenServiceNumber};
            if (_userService.createUser(toAdd) == null)
            {
                string language = Request.Cookies["Language"];
                string lang = Enum.Parse<Language>(language).ToString() ?? "NLD";
                if (lang.Equals("NLD"))
                {
                    ViewData["Error"] = "Er is een fout opgetreden bij het aanmaken van een gebruiker!";

                }
                else
                {
                    ViewData["Error"] = "Error in creating user, please check credentials!";
                }
                return View();
            }
            
            return RedirectToAction("Index", "Home");
        }
    }
}

ESD6NL.DriverSystem/Views/Home/Home.cshtml
@using ESD6NL.DriverSystem.Helpers

@{
    ViewData["Title"] = "Home";
}


<body>

    <div class="container">
        <!-- ROW -->
        <div class="row">   

            <!-- Invoices -->
            <div class="col-lg-4 col-md-6 col-sm-6">
                <a asp-controller="Invoice" asp-action="InvoiceOverview">
                    <div class="card" id="YouTrackCard">
                        <div class="card-body">
                            <h4 class="card-title">@Html.getTerm("Facturen Overzicht")</h4>
                            <p class="card-text">@Html.getTerm("Voor al uw facturen van de afgelopen 5 jaar.")
                            </p>
                        </div>
                    </div>
                </a>
            </div>

            <!-- Payment -->
            <div class="col-lg-4 col-md-6 col-sm-6">
                <a asp-controller="Home" asp-action="PayLastInvoice">
                    <div class="card" id="JenkinsCard">
                        <div class="card-body">
                            <h4 class="card-title">@Html.getTerm("Betalen van laatste Factuur")</h4>
                            <p class="card-text">@Html.getTerm("De laatst onbetaalde factuur meteen betalen.")</p>
                        </div>
                    </div>
                </a>
            </div>

            <!-- MijnRR -->
            <div class="col-lg-4 col-md-6 col-sm-6">
                <a href="#">
                    <div class="card" id="ArtifactoryCard">
                        <div class="card-body">
                            <h4 class="card-title">@Html.getTerm("MijnRR")</h4>
                            <p class="card-text">@Html.getTerm("Controleer uw account gegevens en de auto's die op uw naam zijn geregistreerd.")</p>
                        </div>
                    </div>
                </a>
            </div>

        </div>	<!-- ROW END -->
    </div>
</body>

ESD6NL.DriverSystem/Views/Home/Index.cshtml
@using ESD6NL.DriverSystem.Helpers
@model ESD6NL.DriverSystem.Models.LoginModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="Username">@Html.getTerm("Username")</label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="Password">@Html.getTerm("Password")</label>
                <input asp-for="Password" class="form-control"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>@Html.getTerm("Or") <a asp-controller="Registration" asp-action="Index">@Html.getTerm("register")</a> @Html.getTerm("if you do not yet have a account") </div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}